"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/Button";
import { usePortfolioData, VAULT_YIELD_RATES } from "@/lib/usePortfolioData";
import { formatCurrency } from "@/lib/utils";
import { ABRA } from "@/lib/constants";

/**
 * /earn — the degen/retail front door.
 *
 * Maple Finance insight: two front-ends.
 * Maple Institutional = KYC, large minimums.
 * Syrup.fi = permissionless, any size, just deposit USDC.
 *
 * Abraxas /operate = register your asset, run the agent.
 * Abraxas /earn = just deposit capital, earn from the vault pool.
 * No asset required. No registration. Just yield.
 */

const POOLS = [
  {
    id: "music",
    name: "abraSOUND Pool",
    icon: "♪",
    desc: "Yield from music IP royalty vaults. Backed by streaming distributions, sync licenses, and catalog income.",
    apy: VAULT_YIELD_RATES["490"],
    tvl: 230_700,
    risk: "Medium",
    riskColor: "#f0d98a",
    token: "abraSOUND",
    minDeposit: 50,
    color: "rgba(200,169,110,0.08)",
    border: "rgba(200,169,110,0.3)",
    backedBy: "VAULT-490, VAULT-491, VAULT-494",
  },
  {
    id: "rwa",
    name: "abraYIELD Pool",
    icon: "◈",
    desc: "Diversified yield from real estate rent flows and receivables. Lower volatility, steady income stream.",
    apy: ((VAULT_YIELD_RATES["492"] ?? 6.2) + (VAULT_YIELD_RATES["493"] ?? 9.1)) / 2,
    tvl: 384_200,
    risk: "Low–Medium",
    riskColor: "var(--green)",
    token: "abraYIELD",
    minDeposit: 50,
    color: "rgba(61,214,140,0.06)",
    border: "rgba(61,214,140,0.2)",
    backedBy: "VAULT-492, VAULT-493",
  },
];

type DepositState = "idle" | "input" | "confirming" | "done";

export default function EarnPage() {
  const router = useRouter();
  const portfolio = usePortfolioData();
  const [selected, setSelected] = useState<string | null>(null);
  const [depositState, setDepositState] = useState<DepositState>("idle");
  const [amount, setAmount] = useState("");

  const pool = POOLS.find((p) => p.id === selected);
  const usd = parseFloat(amount) || 0;
  const projected = usd > 0 && pool ? Math.round(usd * (pool.apy / 100)) : 0;

  const handleDeposit = () => {
    setDepositState("confirming");
    setTimeout(() => setDepositState("done"), 1600);
  };

  return (
    <div style={{ maxWidth: "800px", margin: "0 auto", padding: "2.5rem 1.25rem" }}>

      {/* Header */}
      <div style={{ marginBottom: "2.5rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", marginBottom: "0.5rem" }}>
          <p style={{ fontSize: "0.6rem", letterSpacing: "0.18em", textTransform: "uppercase", color: "var(--subtle)" }}>
            Permissionless Yield
          </p>
          <div style={{ display: "flex", alignItems: "center", gap: "0.3rem", background: "rgba(61,214,140,0.08)", border: "1px solid rgba(61,214,140,0.2)", borderRadius: "100px", padding: "0.15rem 0.5rem" }}>
            <span style={{ width: "4px", height: "4px", borderRadius: "50%", background: "var(--green)", animation: "pulse 2s ease-in-out infinite" }} />
            <span style={{ fontSize: "0.58rem", color: "var(--green)", fontWeight: 600 }}>Live</span>
          </div>
        </div>
        <h1 style={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 800, fontSize: "clamp(1.75rem, 5vw, 3rem)", letterSpacing: "-0.02em", marginBottom: "0.75rem" }}>
          Earn from operated assets.
        </h1>
        <p style={{ fontSize: "0.9rem", color: "var(--muted)", maxWidth: "520px", lineHeight: 1.7 }}>
          No asset required. Deposit USDC into a vault pool and earn yield generated by music royalties, real estate, and receivables — all operated by autonomous agents.
        </p>
      </div>

      {/* Stats bar */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "0.75rem", marginBottom: "2rem" }}>
        {[
          { label: "System AUM",      value: portfolio.loading ? "…" : formatCurrency(portfolio.systemAUM) },
          { label: "Avg Pool APY",    value: "7.4–12.8%"  },
          { label: "Min Deposit",     value: "$50 USDC"   },
        ].map((s) => (
          <div key={s.label} style={{ background: "var(--surface)", border: "1px solid var(--line)", borderRadius: "10px", padding: "0.875rem 1.25rem", textAlign: "center" }}>
            <div style={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: "1.1rem", color: "var(--text)", marginBottom: "0.2rem" }}>{s.value}</div>
            <div style={{ fontSize: "0.6rem", letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--subtle)" }}>{s.label}</div>
          </div>
        ))}
      </div>

      {/* Clearpool-inspired: degen vs operator context */}
      <div style={{ background: "var(--surface)", border: "1px solid var(--line)", borderRadius: "12px", padding: "1rem 1.25rem", marginBottom: "2rem", display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: "0.75rem" }}>
        <div>
          <p style={{ fontSize: "0.75rem", fontWeight: 600, marginBottom: "0.2rem" }}>Have an asset to operate?</p>
          <p style={{ fontSize: "0.7rem", color: "var(--subtle)" }}>Register a music catalog, property, or invoice — become a full operator.</p>
        </div>
        <Button size="sm" onClick={() => router.push("/onboard")}>Become an Operator →</Button>
      </div>

      {/* Pool cards */}
      <div style={{ display: "flex", flexDirection: "column", gap: "1rem", marginBottom: "2rem" }}>
        {POOLS.map((p) => (
          <div
            key={p.id}
            style={{
              background: selected === p.id ? p.color : "var(--surface)",
              border: `1px solid ${selected === p.id ? p.border : "var(--line)"}`,
              borderRadius: "14px", padding: "1.5rem",
              cursor: "pointer", transition: "all 0.2s",
            }}
            onClick={() => { setSelected(p.id); setDepositState("input"); setAmount(""); }}
          >
            <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: "0.875rem", flexWrap: "wrap", gap: "0.5rem" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "0.625rem" }}>
                <span style={{ fontSize: "1.5rem" }}>{p.icon}</span>
                <div>
                  <div style={{ fontWeight: 700, fontSize: "0.95rem" }}>{p.name}</div>
                  <div style={{ fontSize: "0.65rem", color: "var(--subtle)", fontFamily: "'JetBrains Mono', monospace", marginTop: "0.1rem" }}>backed by {p.backedBy}</div>
                </div>
              </div>
              <div style={{ textAlign: "right" }}>
                <div style={{ fontWeight: 800, fontSize: "1.4rem", color: "var(--green)", fontFamily: "'Space Grotesk', sans-serif" }}>{p.apy.toFixed(1)}%</div>
                <div style={{ fontSize: "0.6rem", color: "var(--subtle)" }}>APY</div>
              </div>
            </div>

            <p style={{ fontSize: "0.78rem", color: "var(--muted)", lineHeight: 1.6, marginBottom: "0.875rem" }}>{p.desc}</p>

            <div style={{ display: "flex", gap: "1.5rem", fontSize: "0.72rem", flexWrap: "wrap" }}>
              <div><span style={{ color: "var(--subtle)" }}>TVL: </span><span style={{ fontWeight: 600 }}>{formatCurrency(p.tvl)}</span></div>
              <div><span style={{ color: "var(--subtle)" }}>Risk: </span><span style={{ color: p.riskColor, fontWeight: 600 }}>{p.risk}</span></div>
              <div><span style={{ color: "var(--subtle)" }}>Token: </span><span style={{ color: "var(--gold)", fontFamily: "'JetBrains Mono', monospace" }}>{p.token}</span></div>
              <div><span style={{ color: "var(--subtle)" }}>Min: </span><span>${p.minDeposit} USDC</span></div>
            </div>

            {/* Inline deposit if selected */}
            {selected === p.id && depositState === "input" && (
              <div style={{ marginTop: "1.25rem", paddingTop: "1.25rem", borderTop: "1px solid rgba(255,255,255,0.07)" }}>
                <div style={{ display: "flex", gap: "0.625rem", alignItems: "flex-end", flexWrap: "wrap" }}>
                  <div style={{ flex: 1, minWidth: "120px" }}>
                    <label style={{ display: "block", fontSize: "0.6rem", letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--subtle)", marginBottom: "0.4rem" }}>USDC Amount</label>
                    <div style={{ position: "relative" }}>
                      <span style={{ position: "absolute", left: "0.75rem", top: "50%", transform: "translateY(-50%)", color: "var(--muted)", fontSize: "0.875rem" }}>$</span>
                      <input type="number" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="0" min="50"
                        style={{ paddingLeft: "1.5rem", fontSize: "1rem", fontWeight: 600, margin: 0 }} />
                    </div>
                  </div>
                  <Button size="lg" disabled={usd < 50} onClick={(e) => { e.stopPropagation(); handleDeposit(); }}>
                    Deposit {usd >= 50 ? formatCurrency(usd) : ""}
                  </Button>
                </div>
                {usd >= 50 && (
                  <p style={{ fontSize: "0.68rem", color: "var(--green)", marginTop: "0.5rem" }}>
                    Projected: {formatCurrency(projected)}/yr at {p.apy.toFixed(1)}% APY
                  </p>
                )}
              </div>
            )}

            {selected === p.id && depositState === "confirming" && (
              <div style={{ marginTop: "1.25rem", paddingTop: "1.25rem", borderTop: "1px solid rgba(255,255,255,0.07)", textAlign: "center" }}>
                <span style={{ fontSize: "1.25rem", animation: "pulse 1s ease-in-out infinite" }}>⟳</span>
                <p style={{ fontSize: "0.78rem", color: "var(--muted)", marginTop: "0.5rem" }}>Processing deposit…</p>
              </div>
            )}

            {selected === p.id && depositState === "done" && (
              <div style={{ marginTop: "1.25rem", paddingTop: "1.25rem", borderTop: "1px solid rgba(255,255,255,0.07)" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.4rem" }}>
                  <span style={{ color: "var(--green)", fontSize: "1rem" }}>◎</span>
                  <span style={{ fontWeight: 600, fontSize: "0.875rem" }}>Position active.</span>
                </div>
                <p style={{ fontSize: "0.75rem", color: "var(--muted)" }}>
                  {formatCurrency(usd)} earning {p.apy.toFixed(1)}% APY in {p.name}. {p.token} tokens issued to your wallet.
                </p>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* How earn works */}
      <div style={{ background: "var(--surface)", border: "1px solid var(--line)", borderRadius: "14px", padding: "1.5rem", marginBottom: "1.5rem" }}>
        <p style={{ fontSize: "0.62rem", letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--subtle)", marginBottom: "1rem" }}>How earn pools work</p>
        {[
          { n: "1", text: "You deposit USDC into a pool. No registration, no asset required." },
          { n: "2", text: "Your capital is deployed across active vaults in that pool's asset class." },
          { n: "3", text: "Agents operate the underlying assets and capture income distributions." },
          { n: "4", text: "Yield accrues to your position daily. Withdraw anytime." },
          { n: "5", text: "You receive pool tokens (abraSOUND, abraYIELD) representing your share." },
        ].map((s) => (
          <div key={s.n} style={{ display: "flex", gap: "0.875rem", alignItems: "flex-start", padding: "0.5rem 0", borderBottom: "1px solid rgba(255,255,255,0.04)" }}>
            <span style={{ fontFamily: "'Instrument Serif', serif", fontSize: "1.1rem", fontStyle: "italic", color: "var(--gold)", flexShrink: 0, lineHeight: 1.3 }}>{s.n}</span>
            <p style={{ fontSize: "0.78rem", color: "var(--muted)", lineHeight: 1.6 }}>{s.text}</p>
          </div>
        ))}
      </div>

      {/* Safety note */}
      <div style={{ background: "rgba(107,140,255,0.05)", border: "1px solid rgba(107,140,255,0.15)", borderRadius: "10px", padding: "1rem 1.25rem" }}>
        <p style={{ fontSize: "0.72rem", color: "var(--muted)", lineHeight: 1.65 }}>
          <span style={{ color: "#6b8cff", fontWeight: 600 }}>Beta — important. </span>
          Earn pools are currently in simulation mode. Yield shown is projected based on vault APY rates. Real USDC deployment to vault smart contracts will be enabled at graduation. Your deposits are tracked on-chain as Token-2022 positions, but the capital is not yet deployed to live DeFi markets. Never deposit funds you cannot afford to lose in a beta product.
        </p>
      </div>
    </div>
  );
}