#!/usr/bin/env python3
"""Run from project root: python3 fix_vercel_cron.py"""
import base64, os, sys

if not os.path.exists("app"):
    print("Run from project root"); sys.exit(1)

FILES = {
    "vercel.json": "ewogICJmcmFtZXdvcmsiOiAibmV4dGpzIiwKICAiYnVpbGRDb21tYW5kIjogIm5wbSBydW4gYnVpbGQiLAogICJkZXZDb21tYW5kIjogIm5wbSBydW4gZGV2IiwKICAiaW5zdGFsbENvbW1hbmQiOiAibnBtIGluc3RhbGwiLAogICJjcm9ucyI6IFsKICAgIHsKICAgICAgInBhdGgiOiAiL2FwaS9jcm9uL2JhZ3Mtc3luYyIsCiAgICAgICJzY2hlZHVsZSI6ICIwIDAgKiAqICoiCiAgICB9CiAgXQp9Cg==",
    "app/api/cron/bags-sync/route.ts": "Ly8gRklMRTogYXBwL2FwaS9jcm9uL2JhZ3Mtc3luYy9yb3V0ZS50cwovLyBEYWlseSBzeW5jIG9mIGFsbCBCYWdzLXRva2VuaXplZCByZXZlbnVlIGFzc2V0cy4KLy8gVmVyY2VsIEhvYmJ5IHBsYW46IE9ORSBjcm9uIHBlciBkYXkgbWF4aW11bS4KLy8gU2NoZWR1bGU6ICIwIDAgKiAqICoiIChkYWlseSBhdCBtaWRuaWdodCBVVEMpIOKAlCBzZXQgaW4gdmVyY2VsLmpzb24KLy8gUHJvdGVjdGVkIHdpdGggQ1JPTl9TRUNSRVQgZW52IHZhci4KaW1wb3J0IHsgTmV4dFJlcXVlc3QsIE5leHRSZXNwb25zZSB9IGZyb20gIm5leHQvc2VydmVyIjsKaW1wb3J0IHsgc3luY0JhZ3NSZXZlbnVlIH0gICAgICAgICAgIGZyb20gIkAvbGliL3NlcnZpY2VzL2JhZ3NTZXJ2aWNlIjsKCmV4cG9ydCBjb25zdCBkeW5hbWljID0gImZvcmNlLWR5bmFtaWMiOwoKZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIEdFVChyZXE6IE5leHRSZXF1ZXN0KSB7CiAgY29uc3QgY3JvblNlY3JldCA9IHByb2Nlc3MuZW52LkNST05fU0VDUkVUOwogIGNvbnN0IGF1dGhIZWFkZXIgPSByZXEuaGVhZGVycy5nZXQoImF1dGhvcml6YXRpb24iKTsKCiAgaWYgKGNyb25TZWNyZXQgJiYgYXV0aEhlYWRlciAhPT0gYEJlYXJlciAke2Nyb25TZWNyZXR9YCkgewogICAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKHsgZXJyb3I6IlVuYXV0aG9yaXplZCIgfSwgeyBzdGF0dXM6NDAxIH0pOwogIH0KCiAgdHJ5IHsKICAgIGNvbnN0IHJlc3VsdCA9IGF3YWl0IHN5bmNCYWdzUmV2ZW51ZSgpOwogICAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKHsKICAgICAgc3VjY2VzczogIHRydWUsCiAgICAgIHN5bmNlZDogICByZXN1bHQuc3luY2VkLAogICAgICBmYWlsZWQ6ICAgcmVzdWx0LmZhaWxlZCwKICAgICAgc3luY2VkQXQ6IG5ldyBEYXRlKCkudG9JU09TdHJpbmcoKSwKICAgIH0pOwogIH0gY2F0Y2ggKGVycikgewogICAgY29uc3QgbXNnID0gZXJyIGluc3RhbmNlb2YgRXJyb3IgPyBlcnIubWVzc2FnZSA6IFN0cmluZyhlcnIpOwogICAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKHsgc3VjY2VzczpmYWxzZSwgZXJyb3I6bXNnIH0sIHsgc3RhdHVzOjUwMCB9KTsKICB9Cn0K",
    ".github/workflows/ci.yml": "IyBGSUxFOiAuZ2l0aHViL3dvcmtmbG93cy9jaS55bWwKIyBSdW5zIG9uIHB1c2ggdG8gbWFpbiBhbmQgb24gcHVsbCByZXF1ZXN0cyBvbmx5LgojIE5PIHNjaGVkdWxlZCB0cmlnZ2VycyDigJQgYXZvaWRzIGNvbmZsaWN0cyB3aXRoIFZlcmNlbCBhdXRvLWRlcGxveS4KbmFtZTogQ0kKCm9uOgogIHB1c2g6CiAgICBicmFuY2hlczogW21haW5dCiAgcHVsbF9yZXF1ZXN0OgogICAgYnJhbmNoZXM6IFttYWluXQoKam9iczoKICBidWlsZDoKICAgIHJ1bnMtb246IHVidW50dS1sYXRlc3QKICAgIHN0ZXBzOgogICAgICAtIHVzZXM6IGFjdGlvbnMvY2hlY2tvdXRAdjQKCiAgICAgIC0gdXNlczogYWN0aW9ucy9zZXR1cC1ub2RlQHY0CiAgICAgICAgd2l0aDoKICAgICAgICAgIG5vZGUtdmVyc2lvbjogMjAKICAgICAgICAgIGNhY2hlOiBucG0KCiAgICAgIC0gbmFtZTogSW5zdGFsbCBkZXBlbmRlbmNpZXMKICAgICAgICBydW46IG5wbSBjaQoKICAgICAgLSBuYW1lOiBUeXBlIGNoZWNrCiAgICAgICAgcnVuOiBucHggdHNjIC0tbm9FbWl0CiAgICAgICAgY29udGludWUtb24tZXJyb3I6IHRydWUKCiAgICAgIC0gbmFtZTogQnVpbGQKICAgICAgICBydW46IG5wbSBydW4gYnVpbGQKICAgICAgICBlbnY6CiAgICAgICAgICBORVhUX1BVQkxJQ19TVVBBQkFTRV9VUkw6ICAgICAgJHt7IHNlY3JldHMuTkVYVF9QVUJMSUNfU1VQQUJBU0VfVVJMIH19CiAgICAgICAgICBORVhUX1BVQkxJQ19TVVBBQkFTRV9BTk9OX0tFWTogJHt7IHNlY3JldHMuTkVYVF9QVUJMSUNfU1VQQUJBU0VfQU5PTl9LRVkgfX0KICAgICAgICAgIE5FWFRBVVRIX1VSTDogICAgaHR0cHM6Ly9hYnJheGFzLWFwcC52ZXJjZWwuYXBwCiAgICAgICAgICBORVhUQVVUSF9TRUNSRVQ6ICR7eyBzZWNyZXRzLk5FWFRBVVRIX1NFQ1JFVCB9fQogICAgICAgICAgTkVYVF9QVUJMSUNfU09MQU5BX1JQQzogaHR0cHM6Ly9hcGkubWFpbm5ldC1iZXRhLnNvbGFuYS5jb20KICAgICAgICAgIE5FWFRfUFVCTElDX1ZFUklGSUNBVElPTl9QUk9HUkFNX0lEOiBBQlJBWEFTdmVyaWZ5MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMQo=",
}

for path, enc in FILES.items():
    d = os.path.dirname(path)
    if d: os.makedirs(d, exist_ok=True)
    content = base64.b64decode(enc).decode("utf-8")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print(f"WRITTEN  {path}")

print("""
Done. Now:
  git add vercel.json .github/workflows/ci.yml app/api/cron/bags-sync/route.ts
  git commit -m "fix: vercel.json daily cron only, remove 6-hourly blocker"
  git push origin main
  
Then in Vercel dashboard:
  Settings -> Git -> check 'Auto Deploy' is ON for branch 'main'
  Deployments -> trigger one manual deploy to clear any blocked state
""")
