// FILE: lib/design/routeInventory.ts
// Complete route migration inventory for the premium UI redesign.

export type RouteMigrationStatus =
  | "migrated_abx"
  | "migrated_redesign"
  | "migrated_admin"
  | "migrated_partner"
  | "migrated_layout"
  | "migrated_component"
  | "redirect"
  | "pending";

export interface RouteInventoryEntry {
  path: string;
  status: RouteMigrationStatus;
  shell: string;
  notes?: string;
}

/** All app routes and their migration status as of PR #284 follow up */
export const ROUTE_INVENTORY: RouteInventoryEntry[] = [
  { path: "/", status: "migrated_component", shell: "RedesignHome" },
  { path: "/about", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/about/team", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/abra", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/access", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/account", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/admin", status: "migrated_admin", shell: "AdminShell" },
  { path: "/admin/cielo", status: "migrated_admin", shell: "AdminShell" },
  { path: "/admin/connect", status: "migrated_admin", shell: "AdminShell" },
  { path: "/admin/design-partners", status: "migrated_admin", shell: "AdminShell + RedesignPage" },
  { path: "/admin/identity", status: "migrated_admin", shell: "AdminShell" },
  { path: "/admin/inquiries", status: "migrated_admin", shell: "AdminShell + RedesignPage" },
  { path: "/admin/listings", status: "migrated_admin", shell: "AdminShell + RedesignPage" },
  { path: "/admin/partner-flow", status: "migrated_admin", shell: "AdminShell" },
  { path: "/admin/partner-flow/readiness", status: "migrated_admin", shell: "AdminShell" },
  { path: "/admin/partner-sandbox-demo", status: "migrated_admin", shell: "AdminShell" },
  { path: "/admin/partners", status: "migrated_admin", shell: "AdminShell" },
  { path: "/admin/privacy", status: "migrated_admin", shell: "AdminShell" },
  { path: "/admin/receipts", status: "migrated_admin", shell: "AdminShell" },
  { path: "/admin/trust", status: "migrated_admin", shell: "AdminShell" },
  { path: "/agents", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/api/auth/signin", status: "redirect", shell: "n/a" },
  { path: "/api/auth/verify", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/app", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/apps/cielo-sunrise", status: "redirect", shell: "n/a" },
  { path: "/apps/good-trouble", status: "redirect", shell: "n/a" },
  { path: "/apps/music", status: "redirect", shell: "n/a" },
  { path: "/apps/wyoming", status: "redirect", shell: "n/a" },
  { path: "/arena", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/assets/[id]", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/auth/callback", status: "migrated_layout", shell: "AbxSectionLayout (auth)" },
  { path: "/auth/signin", status: "redirect", shell: "n/a" },
  { path: "/auth/verify", status: "migrated_layout", shell: "AbxSectionLayout (auth)" },
  { path: "/auth/zklogin/callback", status: "migrated_layout", shell: "AbxSectionLayout (auth)" },
  { path: "/blog", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/blog/[slug]", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/build", status: "migrated_abx", shell: "AbxPageShell" },
  { path: "/case-studies/chickasaw-project", status: "migrated_component", shell: "RedesignPage (component)" },
  { path: "/case-studies/cielo", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/case-studies/cmn-pokemon-collection", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/case-studies/cpg-grady-270", status: "redirect", shell: "n/a" },
  { path: "/case-studies/smyrna", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/cielo/pay", status: "migrated_layout", shell: "AbxSectionLayout (cielo)" },
  { path: "/cielo/receipt", status: "migrated_layout", shell: "AbxSectionLayout (cielo)" },
  { path: "/cielo/status", status: "migrated_layout", shell: "AbxSectionLayout (cielo)" },
  { path: "/cielo/verified-rate", status: "migrated_abx", shell: "AbxPageShell" },
  { path: "/cielo/verified-rate/confirmation", status: "migrated_abx", shell: "AbxPageShell" },
  { path: "/circuit", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/collect", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/community", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/connect/authorize", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/dashboard", status: "migrated_abx", shell: "AbxPageShell" },
  { path: "/defense", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/demo/partner-access", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/deposit/[vaultId]", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/design-partner", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/developers", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/developers/partner", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/developers/launchpad", status: "migrated_redesign", shell: "RedesignPage + PartnerLaunchpadClient" },
  { path: "/docs", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/docs/*", status: "migrated_redesign", shell: "RedesignPage (all doc routes)" },
  { path: "/earn", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/economics", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/examples/partner-access-starter", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/examples/partner-access-starter/callback", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/examples/partner-access-starter/protected", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/faq", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/flagship", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/formations", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/formations/begin", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/gallery", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/good-trouble", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/good-trouble/checkout", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/good-trouble/enter", status: "migrated_partner", shell: "PartnerEnterClient" },
  { path: "/identity", status: "redirect", shell: "n/a" },
  { path: "/institutional", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/integrate", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/integrations", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/integrations/*", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/investors", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/investors/*", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/legal", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/legal/privacy", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/legal/terms", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/lending", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/list", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/live", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/login", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/mainnet", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/marketplace", status: "migrated_abx", shell: "AbxPageShell" },
  { path: "/methodology", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/metrics", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/minerals", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/missions", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/music-audit", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/onboard", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/operate", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/operator", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/ops/cielo-e2e", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/partner/age-assurance-preview", status: "migrated_partner", shell: "PartnerJourneyLayout" },
  { path: "/partner/continue", status: "migrated_partner", shell: "PartnerJourneyLayout" },
  { path: "/partner/release-gate-preview", status: "migrated_partner", shell: "PartnerJourneyLayout" },
  { path: "/partner/tiered-age-preview", status: "migrated_partner", shell: "PartnerJourneyLayout" },
  { path: "/partner/verify", status: "migrated_partner", shell: "PartnerJourneyLayout" },
  { path: "/partners", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/passport", status: "migrated_abx", shell: "AbxPageShell" },
  { path: "/passport/advanced", status: "migrated_abx", shell: "AbxPageShell" },
  { path: "/passport/[id]", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/payment/success", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/pilot-journey", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/privacy", status: "redirect", shell: "n/a" },
  { path: "/protect", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/roadmap", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/rwa", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/security", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/security/bounty", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/solutions/supply-network", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/sophia", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/stake", status: "redirect", shell: "n/a" },
  { path: "/status", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/swap", status: "migrated_abx", shell: "AbxPageShell" },
  { path: "/terminal", status: "migrated_layout", shell: "AbxSectionLayout (client redirect)" },
  { path: "/token", status: "redirect", shell: "n/a" },
  { path: "/tokenize", status: "redirect", shell: "n/a" },
  { path: "/tokenomics", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/trade", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/train", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/transparency", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/trust-framework", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/use", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/vault", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/vault/[id]", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/verification", status: "migrated_redesign", shell: "RedesignPage" },
  { path: "/verify", status: "migrated_abx", shell: "AbxPageShell" },
  { path: "/verify/[recordId]", status: "migrated_abx", shell: "AbxPageShell" },
  { path: "/verify-asset", status: "redirect", shell: "n/a" },
  { path: "/why", status: "migrated_layout", shell: "AbxSectionLayout" },
  { path: "/withdraw/positionId", status: "migrated_layout", shell: "AbxSectionLayout" },
];

export function pendingRoutes(): RouteInventoryEntry[] {
  return ROUTE_INVENTORY.filter((r) => r.status === "pending");
}

export function migratedRouteCount(): number {
  return ROUTE_INVENTORY.filter((r) => r.status !== "pending").length;
}
