"use client";
// FILE: components/partner/ProvenanceContinueFlow.tsx
// Holder proof interaction for content origin disclosure — plain language, hash-only.

import { useMemo, useState } from "react";
import { Btn } from "@/components/redesign/ui";
import { StatusBanner } from "@/components/ui/StatusBanner";
import { fingerprintArtifactInBrowser } from "@/lib/provenance/clientArtifactFingerprint";
import { buildContentOriginConsentPreview } from "@/lib/provenance/consentPreview";
import type { AiAssistanceCategory } from "@/lib/provenance/types";

const AI_OPTIONS: Array<{ value: AiAssistanceCategory; label: string }> = [
  { value: "none_declared", label: "No AI tools materially contributed" },
  { value: "editing_assistance", label: "AI helped with editing or refinement" },
  { value: "generative_assistance", label: "Generative AI contributed materially" },
  { value: "substantially_generated", label: "Substantially generated by AI" },
];

interface Props {
  partnerName: string;
  partnerId: string;
  policyId: string;
  onSubmitted: () => void;
}

export function ProvenanceContinueFlow({
  partnerName,
  partnerId,
  policyId,
  onSubmitted,
}: Props) {
  const preview = useMemo(() => buildContentOriginConsentPreview(), []);
  const [fileName, setFileName] = useState("");
  const [contentHash, setContentHash] = useState("");
  const [contentType, setContentType] = useState("application/octet-stream");
  const [byteLength, setByteLength] = useState(0);
  const [creatorAttested, setCreatorAttested] = useState(false);
  const [aiCategory, setAiCategory] = useState<AiAssistanceCategory>("none_declared");
  const [hashing, setHashing] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleFileChange(file: File | null) {
    if (!file) return;
    setError(null);
    setHashing(true);
    try {
      const fingerprint = await fingerprintArtifactInBrowser(file);
      setFileName(file.name);
      setContentHash(fingerprint.content_hash);
      setContentType(fingerprint.content_type);
      setByteLength(fingerprint.byte_length);
    } catch {
      setError("Could not fingerprint this file on your device.");
    } finally {
      setHashing(false);
    }
  }

  async function handleSubmit() {
    if (!contentHash || !creatorAttested) {
      setError("Select a file and confirm you created or submitted it.");
      return;
    }
    setSubmitting(true);
    setError(null);
    try {
      const res = await fetch("/api/v1/provenance/submit-disclosure", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          partner_id: partnerId,
          policy_id: policyId,
          content_hash: contentHash,
          content_type: contentType,
          byte_length: byteLength,
          creator_attested: creatorAttested,
          ai_category: aiCategory,
        }),
      });
      const data = await res.json() as { ok?: boolean; error?: string };
      if (!res.ok || !data.ok) {
        setError(data.error ?? "Could not save your disclosure.");
        return;
      }
      onSubmitted();
    } catch {
      setError("Connection problem. Try again.");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div style={{ display: "grid", gap: "1rem" }}>
      <StatusBanner tone="info" title={`${partnerName} is asking about this content.`}>
        {preview.partner_question}
      </StatusBanner>

      <section>
        <h3 style={{ marginBottom: "0.5rem" }}>What they need to know</h3>
        <ul style={{ margin: 0, paddingLeft: "1.1rem" }}>
          <li>Whether you attest that you created or submitted this content</li>
          <li>How AI was used (your disclosure — not a detector result)</li>
          <li>Whether this exact file matches the verified fingerprint</li>
        </ul>
      </section>

      <section>
        <label htmlFor="provenance-file" style={{ display: "block", marginBottom: "0.5rem" }}>
          Select the content file
        </label>
        <input
          id="provenance-file"
          type="file"
          onChange={(event) => void handleFileChange(event.target.files?.[0] ?? null)}
        />
        {hashing ? <p>Computing fingerprint on your device…</p> : null}
        {fileName ? (
          <p style={{ marginTop: "0.5rem" }}>
            Fingerprint ready for <strong>{fileName}</strong>. Abraxas stores the hash only — not the file bytes.
          </p>
        ) : null}
      </section>

      <section>
        <label htmlFor="provenance-ai" style={{ display: "block", marginBottom: "0.5rem" }}>
          How was AI used?
        </label>
        <select
          id="provenance-ai"
          value={aiCategory}
          onChange={(event) => setAiCategory(event.target.value as AiAssistanceCategory)}
        >
          {AI_OPTIONS.map((option) => (
            <option key={option.value} value={option.value}>{option.label}</option>
          ))}
        </select>
      </section>

      <label style={{ display: "flex", gap: "0.5rem", alignItems: "flex-start" }}>
        <input
          type="checkbox"
          checked={creatorAttested}
          onChange={(event) => setCreatorAttested(event.target.checked)}
        />
        <span>I attest that I created or submitted this content.</span>
      </label>

      <section style={{ display: "grid", gap: "0.75rem", gridTemplateColumns: "1fr 1fr" }}>
        <div>
          <h4 style={{ marginBottom: "0.35rem" }}>What Abraxas uses</h4>
          <ul style={{ margin: 0, paddingLeft: "1.1rem" }}>
            <li>SHA-256 fingerprint (hash only)</li>
            <li>Your attestation and AI disclosure</li>
            <li>Integrity check against the fingerprint</li>
          </ul>
        </div>
        <div>
          <h4 style={{ marginBottom: "0.35rem" }}>What {partnerName} receives</h4>
          <ul style={{ margin: 0, paddingLeft: "1.1rem" }}>
            <li>{preview.shared}</li>
          </ul>
          <p style={{ marginTop: "0.5rem", fontSize: "0.9rem" }}>
            Not shared: raw file, email, identity documents, AI scores.
          </p>
        </div>
      </section>

      {error ? <StatusBanner tone="error" title={error} /> : null}

      <Btn
        disabled={submitting || hashing || !contentHash || !creatorAttested}
        onClick={() => void handleSubmit()}
      >
        {submitting ? "Saving disclosure…" : "Continue"}
      </Btn>
    </div>
  );
}
