"use client";
// FILE: components/partner/ProvenanceContinueFlow.tsx
// Holder proof interaction for content origin disclosure — plain language, hash-only.

import { useMemo, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { Btn } from "@/components/redesign/ui";
import { StatusBanner } from "@/components/ui/StatusBanner";
import { PrivacyBoundary, PrivacyBoundaryLegend } from "@/components/protocol/PrivacyBoundary";
import { ProtocolLoadingState } from "@/components/protocol/ProtocolLoadingState";
import {
  PROVENANCE_DISCLOSURE_PATH_STEPS,
  VerificationPath,
  resolveProvenancePathStep,
} from "@/components/protocol/VerificationPath";
import { fingerprintArtifactInBrowser } from "@/lib/provenance/clientArtifactFingerprint";
import { buildContentOriginConsentPreview } from "@/lib/provenance/consentPreview";
import type { AiAssistanceCategory } from "@/lib/provenance/types";
import { abxMotionTransition, abxObjectEnterVariants, abxProofResolveVariants } from "@/lib/motion/abxMotionFramer";

const AI_OPTIONS: Array<{ value: AiAssistanceCategory; label: string; assurance: "l0" | "l0-declaration" }> = [
  { value: "none_declared", label: "No AI tools materially contributed", assurance: "l0-declaration" },
  { value: "editing_assistance", label: "AI helped with editing or refinement", assurance: "l0-declaration" },
  { value: "generative_assistance", label: "Generative AI contributed materially", assurance: "l0-declaration" },
  { value: "substantially_generated", label: "Substantially generated by AI", assurance: "l0-declaration" },
];

interface Props {
  partnerName: string;
  partnerId: string;
  policyId: string;
  onSubmitted: () => void;
}

export function ProvenanceContinueFlow({
  partnerName,
  partnerId,
  policyId,
  onSubmitted,
}: Props) {
  const reduce = useReducedMotion();
  const preview = useMemo(() => buildContentOriginConsentPreview(), []);
  const [fileName, setFileName] = useState("");
  const [contentHash, setContentHash] = useState("");
  const [contentType, setContentType] = useState("application/octet-stream");
  const [byteLength, setByteLength] = useState(0);
  const [creatorAttested, setCreatorAttested] = useState(false);
  const [aiCategory, setAiCategory] = useState<AiAssistanceCategory>("none_declared");
  const [hashing, setHashing] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const pathStep = resolveProvenancePathStep({
    hasFingerprint: Boolean(contentHash),
    creatorAttested,
    submitting,
  });

  const showBoundarySignal = Boolean(contentHash && creatorAttested);

  async function handleFileChange(file: File | null) {
    if (!file) return;
    setError(null);
    setHashing(true);
    try {
      const fingerprint = await fingerprintArtifactInBrowser(file);
      setFileName(file.name);
      setContentHash(fingerprint.content_hash);
      setContentType(fingerprint.content_type);
      setByteLength(fingerprint.byte_length);
    } catch {
      setError("Could not fingerprint this file on your device.");
    } finally {
      setHashing(false);
    }
  }

  async function handleSubmit() {
    if (!contentHash || !creatorAttested) {
      setError("Select a file and confirm you created or submitted it.");
      return;
    }
    setSubmitting(true);
    setError(null);
    try {
      const res = await fetch("/api/v1/provenance/submit-disclosure", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          partner_id: partnerId,
          policy_id: policyId,
          content_hash: contentHash,
          content_type: contentType,
          byte_length: byteLength,
          creator_attested: creatorAttested,
          ai_category: aiCategory,
        }),
      });
      const data = await res.json() as { ok?: boolean; error?: string };
      if (!res.ok || !data.ok) {
        setError(data.error ?? "Could not save your disclosure.");
        return;
      }
      onSubmitted();
    } catch {
      setError("Connection problem. Try again.");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="abx-provenance-flow" style={{ display: "grid", gap: "1.25rem" }}>
      <VerificationPath
        active={pathStep}
        compact
        steps={PROVENANCE_DISCLOSURE_PATH_STEPS}
      />

      <StatusBanner tone="info" title={`${partnerName} is asking about this content.`}>
        {preview.partner_question}
      </StatusBanner>

      <motion.section
        className="abx-provenance-flow__artifact"
        variants={abxObjectEnterVariants({ reduce: !!reduce, tier: "calm" })}
        initial="hidden"
        animate="show"
      >
        <h3 className="abx-provenance-flow__section-title">Select the exact file</h3>
        <p className="abx-provenance-flow__section-lead">
          Abraxas fingerprints the file on your device. Only the hash is stored — never the raw bytes.
        </p>
        <label htmlFor="provenance-file" className="abx-provenance-flow__file-label">
          Content file
        </label>
        <input
          id="provenance-file"
          type="file"
          className="abx-provenance-flow__file-input"
          onChange={(event) => void handleFileChange(event.target.files?.[0] ?? null)}
        />
        {hashing ? (
          <ProtocolLoadingState kind="preparing_request" detail="Computing fingerprint on your device…" />
        ) : null}
        {fileName && contentHash ? (
          <motion.div
            className="abx-provenance-flow__fingerprint abx-provenance-flow__fingerprint--l1"
            variants={abxProofResolveVariants({ reduce: !!reduce })}
            initial="hidden"
            animate="show"
          >
            <span className="abx-provenance-flow__assurance-badge abx-provenance-flow__assurance-badge--l1">
              L1 integrity
            </span>
            <p>
              Fingerprint ready for <strong>{fileName}</strong>
            </p>
            <code className="abx-provenance-flow__hash">{contentHash.slice(0, 16)}…</code>
          </motion.div>
        ) : null}
      </motion.section>

      <motion.section
        className="abx-provenance-flow__attestation"
        variants={abxObjectEnterVariants({ reduce: !!reduce, tier: "calm" })}
        initial="hidden"
        animate={contentHash ? "show" : "hidden"}
        transition={abxMotionTransition("surface", { tier: "calm" })}
      >
        <h3 className="abx-provenance-flow__section-title">Creator attestation</h3>
        <p className="abx-provenance-flow__section-lead abx-provenance-flow__section-lead--l0">
          Your statement — not cryptographic authorship verification.
        </p>
        <label className="abx-provenance-flow__checkbox">
          <input
            type="checkbox"
            checked={creatorAttested}
            onChange={(event) => setCreatorAttested(event.target.checked)}
          />
          <span>I attest that I created or submitted this content.</span>
        </label>
      </motion.section>

      <motion.section
        className="abx-provenance-flow__disclosure"
        variants={abxObjectEnterVariants({ reduce: !!reduce, tier: "calm" })}
        initial="hidden"
        animate={contentHash ? "show" : "hidden"}
        transition={abxMotionTransition("surface", { tier: "calm", delay: 0.04 })}
      >
        <h3 className="abx-provenance-flow__section-title">AI assistance disclosure</h3>
        <p className="abx-provenance-flow__section-lead abx-provenance-flow__section-lead--l0">
          Your declaration — Abraxas does not detect or score AI usage.
        </p>
        <label htmlFor="provenance-ai" className="abx-provenance-flow__file-label">
          How was AI used?
        </label>
        <select
          id="provenance-ai"
          className="abx-provenance-flow__select"
          value={aiCategory}
          onChange={(event) => setAiCategory(event.target.value as AiAssistanceCategory)}
        >
          {AI_OPTIONS.map((option) => (
            <option key={option.value} value={option.value}>{option.label}</option>
          ))}
        </select>
      </motion.section>

      <PrivacyBoundary
        compact
        signalActive={showBoundarySignal}
        protectedItems={[
          "SHA-256 fingerprint (hash only)",
          "Your attestation and AI disclosure",
          "Integrity evaluation against fingerprint",
        ]}
        disclosedLabel={preview.shared}
        disclosedResult={showBoundarySignal ? "Provenance result prepared" : undefined}
      />
      <PrivacyBoundaryLegend>
        Raw file bytes, identity documents, and AI detector scores never cross this boundary.
      </PrivacyBoundaryLegend>

      {error ? <StatusBanner tone="error" title={error} /> : null}

      <Btn
        disabled={submitting || hashing || !contentHash || !creatorAttested}
        onClick={() => void handleSubmit()}
      >
        {submitting ? "Saving disclosure…" : "Continue"}
      </Btn>
    </div>
  );
}
