import { NextResponse } from "next/server";
import { fetchAbraStats } from "@/lib/bags";

/**
 * GET /api/bags/revenue
 *
 * Public revenue snapshot for the ABRA token, pulled live from Bags.
 * - lifetimeFees: total fees generated by the ABRA token (creator earnings)
 * - partner:      partner-level claimed + unclaimed fees
 * - tokenMint:    ABRA contract address (provenance)
 *
 * This endpoint is intentionally public — judges and users can verify
 * the same numbers by hitting Bags directly with their own API key.
 */
export async function GET() {
  try {
    const data = await fetchAbraStats();
    return NextResponse.json({ ok: true, ...data });
  } catch (err) {
    console.error("[api/bags/revenue] error:", err);
    return NextResponse.json(
      { ok: false, error: "Failed to fetch revenue stats" },
      { status: 500 }
    );
  }
}
