"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { PageHeader } from "@/components/PageHeader";
import { WalletGate } from "@/components/WalletGate";
import { usePortfolioData } from "@/lib/usePortfolioData";
import { formatCurrency } from "@/lib/utils";

type AState = "idle" | "confirming" | "confirmed";

const ACTIONS = [
  { icon: "↓", title: "Withdraw", desc: "Transfer capital to your connected wallet.", key: "withdraw" },
  { icon: "↺", title: "Reinvest", desc: "Compound yield back into active vault positions.", key: "reinvest" },
  { icon: "⇄", title: "Swap", desc: "Exchange capital for $ABRA or supported tokens.", key: "swap" },
  { icon: "↗", title: "New Position", desc: "Deploy capital to a vault in the marketplace.", key: "position", href: "/marketplace" },
] as const;

function UseValueContent() {
  const router = useRouter();
  const portfolio = usePortfolioData();
  const [states, setStates] = useState<Record<string, AState>>({});

  const handle = (key: string, href?: string) => {
    if (href) { router.push(href); return; }
    setStates((s) => ({ ...s, [key]: "confirming" }));
    setTimeout(() => {
      setStates((s) => ({ ...s, [key]: "confirmed" }));
      setTimeout(() => setStates((s) => ({ ...s, [key]: "idle" })), 2500);
    }, 1200);
  };

  const txns = portfolio.vaultPositions.slice(0, 3).map((p) => ({
    label: `Yield credited — ${p.vaultName}`,
    amount: Math.round(p.annualYield / 12),
    type: "credit" as const,
  })).concat([{
    label: "Withdrawal to wallet",
    amount: Math.round(portfolio.availableCapital * 0.4),
    type: "debit" as const,
  }]);

  return (
    <div style={{ maxWidth: "760px", margin: "0 auto", padding: "2.5rem 1.5rem" }}>
      <PageHeader title="Use Your Capital" subtitle="Access yield generated by your vault positions." />

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.75rem", marginBottom: "2rem" }}>
        {[
          { label: "Available Capital", value: portfolio.loading ? "…" : formatCurrency(portfolio.availableCapital), color: "var(--gold)" },
          { label: "Yield Generated",   value: portfolio.loading ? "…" : formatCurrency(portfolio.yieldGenerated),  color: "var(--green)" },
        ].map((card) => (
          <div key={card.label} style={{ background: "var(--surface)", border: "1px solid var(--line)", borderRadius: "14px", padding: "1.25rem 1.5rem" }}>
            <div style={{ fontSize: "0.62rem", letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--subtle)", marginBottom: "0.5rem" }}>{card.label}</div>
            <div style={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: "1.6rem", color: card.color, transition: "all 0.5s" }}>{card.value}</div>
          </div>
        ))}
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.75rem", marginBottom: "2rem" }}>
        {ACTIONS.map((item) => {
          const state = states[item.key] ?? "idle";
          return (
            <div
              key={item.key}
              onClick={() => handle(item.key, "href" in item ? item.href : undefined)}
              style={{
                background: state === "confirmed" ? "rgba(61,214,140,0.05)" : "var(--surface)",
                border: `1px solid ${state === "confirmed" ? "rgba(61,214,140,0.3)" : state === "confirming" ? "rgba(200,169,110,0.3)" : "var(--line)"}`,
                borderRadius: "14px", padding: "1.5rem", cursor: "pointer", transition: "all 0.3s",
              }}
              onMouseEnter={(e) => { if (state === "idle") (e.currentTarget as HTMLElement).style.borderColor = "rgba(200,169,110,0.25)"; }}
              onMouseLeave={(e) => { if (state === "idle") (e.currentTarget as HTMLElement).style.borderColor = "var(--line)"; }}
            >
              <div style={{ width: "32px", height: "32px", borderRadius: "8px", background: "rgba(200,169,110,0.07)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "0.95rem", marginBottom: "0.875rem" }}>
                {state === "confirming" ? "⟳" : state === "confirmed" ? "✓" : item.icon}
              </div>
              <div style={{ fontWeight: 600, fontSize: "0.9rem", marginBottom: "0.25rem" }}>{item.title}</div>
              <div style={{ fontSize: "0.75rem", color: "var(--muted)", lineHeight: 1.5 }}>
                {state === "confirming" ? "Processing…" : state === "confirmed" ? "Confirmed." : item.desc}
              </div>
            </div>
          );
        })}
      </div>

      <div style={{ background: "var(--surface)", border: "1px solid var(--line)", borderRadius: "14px", padding: "1.5rem" }}>
        <div style={{ fontSize: "0.7rem", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.08em", color: "var(--muted)", marginBottom: "1rem" }}>Recent Transactions</div>
        {txns.map((tx, i) => (
          <div key={i} style={{ display: "flex", justifyContent: "space-between", padding: "0.7rem 0", borderBottom: i < txns.length - 1 ? "1px solid var(--line)" : "none", fontSize: "0.82rem" }}>
            <span style={{ color: "var(--muted)" }}>{tx.label}</span>
            <span style={{ fontWeight: 600, color: tx.type === "credit" ? "var(--green)" : "var(--red)" }}>
              {tx.type === "credit" ? "+" : "−"}{formatCurrency(tx.amount)}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

export default function UsePage() {
  return <WalletGate><UseValueContent /></WalletGate>;
}