"use client";

import { useRouter } from "next/navigation";
import { PageHeader } from "@/components/PageHeader";
import { Button } from "@/components/Button";
import { WalletGate } from "@/components/WalletGate";
import { useToast } from "@/lib/toastState";
import { userStats } from "@/lib/mockData";
import { formatCurrency } from "@/lib/utils";

const useActions = [
  { icon: "↓", title: "Withdraw", desc: "Move capital to your connected wallet or bank account.", action: "Withdraw" },
  { icon: "↺", title: "Reinvest", desc: "Compound yield back into operating vaults.", action: "Reinvest" },
  { icon: "⇄", title: "Swap", desc: "Exchange capital for $ABRA or other supported tokens.", action: "Swap" },
  { icon: "↗", title: "New Position", desc: "Deploy capital to a vault from the marketplace.", action: "Position", href: "/marketplace" },
];

const recentTransactions = [
  { label: "Yield credited — VAULT-490", amount: 2100, type: "credit" as const },
  { label: "Activation bonus", amount: 500, type: "credit" as const },
  { label: "Yield credited — VAULT-491", amount: 8400, type: "credit" as const },
  { label: "Withdrawal to wallet", amount: 3200, type: "debit" as const },
];

function UseValueContent() {
  const { showToast } = useToast();
  const router = useRouter();

  const handleAction = (action: string, href?: string) => {
    if (href) {
      router.push(href);
      return;
    }
    showToast(`${action} — Transaction confirmed (mock). Capital moved.`);
  };

  return (
    <div className="max-w-3xl mx-auto px-4 py-10">
      <PageHeader
        title="Use Your Capital"
        subtitle="Access yield generated by your vault positions. Withdraw, reinvest, swap, or open a new position."
      />

      <div className="grid grid-cols-2 gap-4 mb-8">
        <div className="bg-bg-2 border border-border rounded-card p-5">
          <p className="text-[0.68rem] text-abraxas-subtle uppercase tracking-wider mb-2">
            Available Capital
          </p>
          <p className="font-display font-bold text-2xl text-gold">
            {formatCurrency(userStats.availableCapital)}
          </p>
        </div>
        <div className="bg-bg-2 border border-border rounded-card p-5">
          <p className="text-[0.68rem] text-abraxas-subtle uppercase tracking-wider mb-2">
            Yield Generated
          </p>
          <p className="font-display font-bold text-2xl text-abraxas-green">
            {formatCurrency(userStats.yieldGenerated)}
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8">
        {useActions.map((item) => (
          <div key={item.title}
            className="bg-bg-2 border border-border rounded-card p-6 cursor-pointer hover:border-gold transition-colors"
            onClick={() => handleAction(item.action, item.href)}>
            <div className="w-9 h-9 rounded-lg bg-gold-dim flex items-center justify-center text-lg mb-4">
              {item.icon}
            </div>
            <h3 className="font-display font-semibold text-[0.95rem] mb-1">{item.title}</h3>
            <p className="text-xs text-abraxas-muted leading-relaxed">{item.desc}</p>
          </div>
        ))}
      </div>

      <div className="bg-bg-2 border border-border rounded-card p-6">
        <h2 className="font-display font-semibold text-sm mb-4">Recent Transactions</h2>
        <div className="divide-y divide-border">
          {recentTransactions.map((tx, i) => (
            <div key={i} className="flex items-center justify-between py-3 text-sm">
              <span className="text-abraxas-muted">{tx.label}</span>
              <span className={tx.type === "credit" ? "text-abraxas-green font-medium" : "text-abraxas-red font-medium"}>
                {tx.type === "credit" ? "+" : "−"}{formatCurrency(tx.amount)}
              </span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default function UsePage() {
  return <WalletGate><UseValueContent /></WalletGate>;
}
