// FILE: lib/custody/dataCustodyMap.ts
// Authoritative Abraxas data-custody inventory (code-level audit map).

import type { DataCustodyEntry } from "./types";

export const DATA_CUSTODY_MAP: readonly DataCustodyEntry[] = [
  {
    id: "dob_l0_transient",
    dataType: "Date of birth (L0 self-attestation input)",
    origin: "Holder browser form",
    processor: "submitSelfAttestation",
    currentStorage: "Transient request memory only",
    retention: "Discarded after deriveSelfAttestedAgeBand()",
    access: "Request handler only",
    necessity: "Required once to derive age band; not reusable evidence",
    storageClass: "raw_evidence",
    auditClass: "A_ephemeral",
    rawNecessary: true,
  },
  {
    id: "self_attestation_ledger",
    dataType: "Self-attested age band (over_21 | under_21)",
    origin: "Derived from transient DOB",
    processor: "selfAttestationLedger",
    currentStorage: "self_attestation_ledger.age_band",
    retention: "TTL default 24h (SELF_ATTESTED_AGE_TTL_HOURS)",
    access: "service_role; policy evaluation",
    necessity: "L0 browse/purchase gate; not government-ID proof",
    storageClass: "derived_fact",
    auditClass: "D_policy_outcome",
    rawNecessary: false,
  },
  {
    id: "gt_dob_prequal_cookie",
    dataType: "Purchase DOB prequal cookie (age_band + flow IDs)",
    origin: "dob-prequal route",
    processor: "goodTroublePurchaseDobCookie",
    currentStorage: "HttpOnly cookie abraxas_gt_dob_prequal",
    retention: "30 minutes",
    access: "Same-origin server",
    necessity: "Prequal gate only; not authoritative checkout proof",
    storageClass: "derived_fact",
    auditClass: "A_ephemeral",
    rawNecessary: false,
  },
  {
    id: "passport_documents_raw",
    dataType: "ID document images, legal name, email",
    origin: "Holder capture upload",
    processor: "identity capture / passport_documents",
    currentStorage: "passport_documents + passport-documents bucket",
    retention: "Until RAW_IDENTITY_EVIDENCE_RETENTION_DAYS purge",
    access: "Admin review; never partners",
    necessity: "L2+ identity verification; purge after review window",
    storageClass: "raw_evidence",
    auditClass: "B_raw_identity_evidence",
    rawNecessary: true,
  },
  {
    id: "identity_review_sessions",
    dataType: "Review session metadata + evidence_content_hash",
    origin: "Capture session",
    processor: "identity review pipeline",
    currentStorage: "identity_review_sessions",
    retention: "Immutable audit; raw purge scheduled separately",
    access: "Operators; service_role",
    necessity: "Fraud prevention and review audit without storing PII fields",
    storageClass: "audit_metadata",
    auditClass: "C_minimized_audit_metadata",
    rawNecessary: false,
  },
  {
    id: "age_evidence_records",
    dataType: "Age evidence decision + provider_reference_hash",
    origin: "IDV / biometric path",
    processor: "ageEvidence service",
    currentStorage: "age_evidence_records",
    retention: "Until superseded/revoked/expired",
    access: "Policy evaluation; operators",
    necessity: "Linkage and assurance without DOB storage",
    storageClass: "audit_metadata",
    auditClass: "C_minimized_audit_metadata",
    rawNecessary: false,
  },
  {
    id: "credential_claims",
    dataType: "Normalized policy claims (e.g. product_eligibility over_21)",
    origin: "Issuance after verification",
    processor: "claimsService",
    currentStorage: "credential_claims.claim_value (jsonb)",
    retention: "Until expiry/revocation",
    access: "Policy evaluation; claim refs to partners",
    necessity: "Reusable facts without underlying evidence",
    storageClass: "credential",
    auditClass: "D_policy_outcome",
    rawNecessary: false,
  },
  {
    id: "content_artifact_hash",
    dataType: "Content artifact SHA-256 fingerprint",
    origin: "Holder-submitted media buffer",
    processor: "artifactFingerprint",
    currentStorage: "content_artifact_records.content_hash",
    retention: "Until revoked/superseded",
    access: "Provenance evaluation",
    necessity: "Integrity binding without retaining raw media",
    storageClass: "commitment",
    auditClass: "D_policy_outcome",
    rawNecessary: false,
  },
  {
    id: "decision_receipts",
    dataType: "Signed eligibility decision receipt",
    origin: "Policy evaluation",
    processor: "decisionReceipts service",
    currentStorage: "decision_receipts",
    retention: "Immutable audit",
    access: "Partners via public/partner API; pseudonym only",
    necessity: "Partner-verifiable narrow result",
    storageClass: "receipt",
    auditClass: "E_partner_artifact",
    rawNecessary: false,
  },
  {
    id: "partner_webhooks",
    dataType: "Partner webhook notification payload",
    origin: "Event delivery",
    processor: "webhookPayloadContract",
    currentStorage: "Transient delivery + delivery audit metadata",
    retention: "Delivery logs metadata-only",
    access: "Partner HMAC endpoint",
    necessity: "Notification to re-fetch receipt; not proof",
    storageClass: "public_result",
    auditClass: "E_partner_artifact",
    rawNecessary: false,
  },
  {
    id: "zklogin_identity",
    dataType: "OAuth sub, email, user_salt",
    origin: "Google OAuth",
    processor: "sui_zklogin_identities",
    currentStorage: "sui_zklogin_identities",
    retention: "Account lifetime; no auto-purge in current release",
    access: "Auth/session; not partner-visible",
    necessity: "Account recovery and wallet derivation",
    storageClass: "encrypted_holder_evidence",
    auditClass: "F_account_immutable_ops",
    rawNecessary: false,
  },
  {
    id: "chain_attestation_commitments",
    dataType: "Partner/policy/subject hash commitments",
    origin: "Chain attestation adapter",
    processor: "chainAttestation / chainCommitments",
    currentStorage: "Optional on-chain anchor + off-chain signed attestation",
    retention: "Chain-dependent; hashes only",
    access: "Public chain reads hashes; no PII",
    necessity: "Optional verifiable status anchor",
    storageClass: "commitment",
    auditClass: "E_partner_artifact",
    rawNecessary: false,
  },
  {
    id: "browser_session",
    dataType: "Browser session JWT (sui address)",
    origin: "Hosted holder bootstrap",
    processor: "browserSession",
    currentStorage: "HttpOnly cookie abraxas_browser_session",
    retention: "7 days",
    access: "API auth",
    necessity: "Session continuity; not eligibility proof",
    storageClass: "audit_metadata",
    auditClass: "A_ephemeral",
    rawNecessary: false,
  },
  {
    id: "partner_verify_resume",
    dataType: "Partner flow resume state",
    origin: "Partner verify UI",
    processor: "partnerVerifyResume",
    currentStorage: "sessionStorage abraxas_partner_verify_resume_v1",
    retention: "30 minutes",
    access: "Same browser tab",
    necessity: "Flow continuity; explicitly no PII/tokens",
    storageClass: "audit_metadata",
    auditClass: "A_ephemeral",
    rawNecessary: false,
  },
];

export function custodyEntryById(id: string): DataCustodyEntry | undefined {
  return DATA_CUSTODY_MAP.find((entry) => entry.id === id);
}

export function entriesByStorageClass(storageClass: DataCustodyEntry["storageClass"]): DataCustodyEntry[] {
  return DATA_CUSTODY_MAP.filter((entry) => entry.storageClass === storageClass);
}

export function entriesByAuditClass(auditClass: DataCustodyEntry["auditClass"]): DataCustodyEntry[] {
  return DATA_CUSTODY_MAP.filter((entry) => entry.auditClass === auditClass);
}
